import './globals.css'
import { Montserrat } from 'next/font/google'
import Link from 'next/link';

const montserrat = Montserrat({ weight:["400","700"],subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} mx-32 my-12`}>
      <nav>
          <h1>logo</h1>
          <ul className="font-semibold">
            <li className="underline hover:bg-blue-500"><Link href="/">Home</Link></li>
            <li className="underline hover:bg-blue-500"><Link href="/about">About</Link></li>
          </ul>
        </nav>
        {children}
        </body>
    </html>
  )
}